# config file version
apiVersion: 1

datasources:
  - name: prometheus-metrics
    editable: true
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090/
    isDefault: true
 