{
 "title": "MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database size (GB)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_dataSize{database=\"mydb\"} / 100000000",
     "legendFormat": "ShortenerStore"
    }
   ]
  },
  {
   "title": "Memory (GB)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 100000000",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_alloc_bytes_total / 100000000",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "go_threads" }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds_sum", "legendFormat": "duration (s)" }
   ]
  },
  {
   "title": "Total documents in collection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_count{collection=\"transactions\",database=\"mydb\"}",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Total documents in collection (GB)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_size{database=\"mydb\"} / 100000000",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Latency (R/W)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_collstats_latencyStats_commands_latency)",
     "legendFormat": "commands"
    },
    {
     "expr": "sum(mongodb_collstats_latencyStats_transactions_latency)",
     "legendFormat": "transactions"
    },
    {
     "expr": "sum(mongodb_collstats_latencyStats_reads_latency)",
     "legendFormat": "reads"
    }
   ]
  }
 ]
}